[application]
name = "RejectionRoulette"
asset_dir = "assets"

[web.app]
title = "RejectionRoulette"

[web.resource]
style = ["assets/styling/main.scss"]
script = []

[web.resource.dev]
script = []

[bundle]
publisher = "Cavenfish"
identifier = "com.rr"
icon = [
    "assets/icons/rr_16x16.png",
    "assets/icons/rr_32x32.png",
    "assets/icons/rr_64x64.png",
    "assets/icons/rr_256x256.png"
]