[application]
name = "RejectionRoulette"
asset_dir = "assets"

[web.app]
title = "RejectionRoulette"

[web.resource]
style = ["assets/styling/main.scss"]
script = []

[web.resource.dev]
script = []

[bundle]
publisher = "Cavenfish"
identifier = "com.rr"
icon = ["assets/icons/rr.png"]