name: CI

on:
  push:
    branches:
      - main

jobs:
  bundle:
    name: Bundle (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: linux-bundle
            bundle_path: target/dx/rejection_roulette/release/bundle/deb/*.deb
          - os: windows-latest
            artifact_name: windows-bundle
            bundle_path: target/dx/rejection_roulette/release/bundle/msi/*.msi
          - os: macos-latest
            artifact_name: macos-bundle
            bundle_path: target/dx/rejection_roulette/release/bundle/osx/*.app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli

      - name: Run Dioxus Bundle
        run: dx bundle --release --desktop

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.bundle_path }}
